---
title: "Plot means over time"
format: html
editor: visual
---

```{r}

knitr::opts_chunk$set(error = TRUE)

library(tidyverse)
library(mgm)
library(qgraph)
library(psych)
library(corrr)
library(here)

``` 

```{r}

data_all_timepoints <- read_rds(file = here('4 Generated Datasets','Vars_At_All_Timepoints.rds'))

```

```{r}

data.PrePostFU.long <- 
  data_all_timepoints %>%
  
  # not analyzing CESD so drop this variable
  select(-CESD) %>% 
  
  # just Pre Post data
  filter(timepoint %in% c(1,3,5)) %>%
  
  # reshape data
  pivot_longer(cols = HADS.A:AAQc) %>%
  pivot_wider(names_from = c('name','timepoint')) %>%
  mutate(.rownames = as.character(c(1:nrow(.)))) %>%
  relocate(.rownames) %>%
  drop_na()  %>%
  pivot_longer(cols = HADS.A_1:AAQc_5, names_to = c("instrument", "timepoint"), names_sep = "_")


```

HADS – M (SD)
CARS– M (SD)
IES-R– M (SD)
AAQc – M (SD)
SCS – M (SD)



```{r}

plot <- data.PrePostFU.long %>%
  mutate(Condition = ifelse(Condition_Dummy == 0, "MEUC", "ACT"),
         instrument = str_replace_all(instrument, pattern = c(
           "EAC.Total" = "EAC",
           "IESR.Total" = "IES-R",
           "HADS.A" = "HADS"))) %>%
  
  ungroup() %>%
  mutate(Timepoint = as_factor(
    ifelse(timepoint == 1, "Pre",
           ifelse(timepoint == 3, "Post", "FU")))) %>%
  group_by(instrument, Timepoint,Condition) %>%
  summarize(mean = mean(value),
            sd = sd(value)) %>%
  
  ggplot(aes(x = Timepoint, color = Condition)) +
  geom_point(aes(y = mean)) +
  geom_line(aes(y = mean)) +
  geom_errorbar(aes(ymin=mean-sd, 
                    ymax=mean+sd)) +
  theme_minimal() +
  ylab('') +
  
  facet_wrap(facet = vars(instrument), nrow = 3, ncol = 2, scales = "free")


plot
```




```{r}
ggsave(filename = here('5 Tables and Figures', "Pre Mid Post Means and SDs Plot.jpg"), units = "in", width = 4, height = 6, dpi = 300)

```
