---
title: "Create Bootstrapped Network Model Table"
output: html_notebook
---

TODO:
- ensure 70% is the "right" cutoff
- do some cell highlighting per 70% cutoff
- put in lines to separate adjacent models from longer term models

# Read in libraries and data
```{r}

library(tidyverse)
library(kableExtra)
library(here)

PreToMid.fit <- read_rds(here('Fitted model objects','PreToMid.fit.boot'))
MidToPost.fit <- read_rds(here('Fitted model objects','MidToPost.fit.boot'))
PostTo3MFU.fit <- read_rds(here('Fitted model objects','PostTo3MFU.fit.boot'))
my3mTo6mFU.fit <- read_rds(here('Fitted model objects','my3mTo6mFU.fit.boot'))

PreToPost.fit <- read_rds(here('Fitted model objects','PreToPost.fit.boot'))
PreTo6mFU.fit <- read_rds(here('Fitted model objects','PreTo6mFU.fit.boot'))

```




# Function for obtaining estimates and quantiles

Uses part of https://github.com/cran/mgm/blob/master/R/plotRes.R
```{r}


getEdgeEstimates <- function(object, model_name){
  
  # the following is copied from Jonas's code
  
  quantiles <- c(.05, .95)
  
  dims <- dim(object$bootParameters)
    p <- dims[1]
    nB <- dims[3]
    n_pars <- p*(p-1) / 2
    
    # Collapse into edge x property matrix
    tar_mat <- matrix(NA, nrow=n_pars, ncol = 6)
    colnames(tar_mat) <- c("Variable A", "Variable B", "Mean", "qtl_low", "qtl_high", "propLtZ")
    
    counter <- 1
    for(row in 1:p) {
      for(col in row:p) {
        if(row!=col){
          
          # Variable ids
          tar_mat[counter, 1] <- row
          tar_mat[counter, 2] <- col
          
          # Quantiles
          qtls <- quantile(object$bootParameters[row, col, ], probs = quantiles)
          tar_mat[counter, 3] <- mean(object$bootParameters[row, col, ])
          tar_mat[counter, 4] <- qtls[1]
          tar_mat[counter, 5] <- qtls[2]
          tar_mat[counter, 6] <- mean(abs(object$bootParameters[row, col, ]) > 0) # proportion estimates > 0
          
          # update counter
          counter <- counter + 1
        }
      }
    }
    
    # now that the matrix is completed, new code to turn it into a tibble with my variable names embedded
    
    variable_names <- tibble(numbers = as.double(c(1:7)),
                             names = c( 'ACTorMEUC', 'HADS','IESR', 'FCR', 'SCS', 'EAC', 'AAQc'))
    
    EdgeWeights <-
      tar_mat %>%
      as_tibble %>%
      
      # pull in variable names for each variable column
      left_join(variable_names, by = c ("Variable A" = "numbers")) %>%
      select(-`Variable A`) %>%
      rename(`Variable 1` = names) %>%
      left_join(variable_names, by = c ("Variable B" = "numbers")) %>%
      select(-`Variable B`) %>%
      rename(`Variable 2` = names) %>%
      
      # rearrange column order
      relocate(`Variable 2`, .before = Mean) %>%
      relocate(`Variable 1`, .before = `Variable 2`) %>%
      
      # rename columns
      rename(`Mean Estimate of Edge Weight` = Mean,
            `5%` = qtl_low,
             `95%` = qtl_high,
             `% Samples Where Edge Was Nonzero` = propLtZ) %>%
      mutate(`Model` = model_name)
    
    return(EdgeWeights)
    
}

```

# Print table 
```{r}

to_print <- 
bind_rows(
  getEdgeEstimates(PreToMid.fit, "1 - Pre to Mid"),
  getEdgeEstimates(MidToPost.fit, "2 - Mid to Post"),
  getEdgeEstimates(PostTo3MFU.fit, "3 - Post to 3M FU"),
  getEdgeEstimates(my3mTo6mFU.fit, "4 - 3M to 6M FU"),
  getEdgeEstimates(PreToPost.fit, "5 - Pre to Post"),
  getEdgeEstimates(PreTo6mFU.fit, "6 - Pre to 6M FU")) %>%
  pivot_wider(names_from = `Model`, values_from = c(`Mean Estimate of Edge Weight`:`% Samples Where Edge Was Nonzero`),     names_glue = "{Model} {.value}") %>%
  
  relocate(starts_with("1 - "), .before = starts_with("2 - ")) %>%
  relocate(starts_with("2 - "), .before = starts_with("3 - ")) %>%
  relocate(starts_with("3 - "), .before = starts_with("4 - ")) %>%
  relocate(starts_with("4 - "), .before = starts_with("5 - ")) %>%
  relocate(starts_with("5 - "), .before = starts_with("6 - "))
  
to_print %>%
  kable(escape = F, 
        align = "c", 
        caption = 'Bootstrapped Models', 
        digits = 2, 
        col.names = c("Variable 1", "Variable 2", rep(c("Est","5%","95%", "% Samples Where Nonzero"),times = 6))) %>%
  #kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = F) %>%
 # kable_classic(html_font = 'Times New Roman', full_width = FALSE) %>%
  kable_paper() %>%
  add_header_above(c(" " = 2, 
                   "Pre to Mid" = 4, 
                   "Mid to Post" = 4,
                   "Post to 3M FU" = 4,
                   "3M FU to 6M FU" = 4,
                   "Pre to Post" = 4,
                   "Pre to 6m FU" = 4)) %>%
  # do first four columns
  column_spec(3:6, background = ifelse(to_print$`1 - Pre to Mid % Samples Where Edge Was Nonzero` > .7, 
                                       "red", "white"),
              color = ifelse(to_print$`1 - Pre to Mid % Samples Where Edge Was Nonzero` > .7, 
                                       "white", "grey")) %>%
    # do second four columns
  column_spec(7:10, background = ifelse(to_print$`2 - Mid to Post % Samples Where Edge Was Nonzero` > .7, 
                                       "red", "white"),
              color = ifelse(to_print$`2 - Mid to Post % Samples Where Edge Was Nonzero` > .7, 
                                       "white", "grey")) %>%
      # do third four columns
  column_spec(11:14, background = ifelse(to_print$`3 - Post to 3M FU % Samples Where Edge Was Nonzero` > .7, 
                                       "red", "white"),
              color = ifelse(to_print$`3 - Post to 3M FU % Samples Where Edge Was Nonzero` > .7, 
                                       "white", "grey")) %>%
        # do 4th four columns
  column_spec(15:18, background = ifelse(to_print$`4 - 3M to 6M FU % Samples Where Edge Was Nonzero` > .7, 
                                       "red", "white"),
              color = ifelse(to_print$`4 - 3M to 6M FU % Samples Where Edge Was Nonzero` > .7, 
                                       "white", "grey")) %>%
        # do 5th four columns
  column_spec(19:22, background = ifelse(to_print$`5 - Pre to Post % Samples Where Edge Was Nonzero` > .7, 
                                       "red", "white"),
              color = ifelse(to_print$`5 - Pre to Post % Samples Where Edge Was Nonzero` > .7, 
                                       "white", "grey")) %>%
          # do 6th four columns
  column_spec(23:26, background = ifelse(to_print$`6 - Pre to 6M FU % Samples Where Edge Was Nonzero` > .7, 
                                       "red", "white"),
              color = ifelse(to_print$`6 - Pre to 6M FU % Samples Where Edge Was Nonzero` > .7, 
                                       "white", "grey"))
  
                                       

```

