---
title: "ANCOVA Equivalent Mediation Models"
output: html_notebook
---

# read data and libraries

```{r}

library(tidyverse)
library(here)
library(lavaan)


PreToPost.data <- readRDS(file = here('4 Generated Datasets','Vars_At_All_Timepoints.rds')) %>%
  as_tibble() %>%
  select(-CESD) %>%
  pivot_longer(cols = HADS.A:AAQc) %>%
  filter(timepoint %in% c(1,3)) %>%
  pivot_wider(names_from = timepoint:name, names_glue = "{name}_T{timepoint}") %>%
  filter(complete.cases(.))
```

# Standardize scores

```{r}

# PreToPost.data.standardized <-
#   PreToPost.data %>%
#   mutate(across(.cols = HADS.A:AAQc, .fns = scale))

```

# Generic mediation model

```{r}

runMediationModel <- function(mediator_var, outcome_var) {
  mediation.model.generic <- ANOVA.model.generic <- '
# latent mediator change variable
mediator_change =~   1*MediatorVariable_T3
mediator_change ~ mediator_change_mean*1
mediator_change ~~ mediator_variance*mediator_change


MediatorVariable_T3 ~ 1*MediatorVariable_T1
MediatorVariable_T3 ~~ 0*MediatorVariable_T1
MediatorVariable_T3 ~~ 0*MediatorVariable_T3
MediatorVariable_T3 ~ 0
MediatorVariable_T1 ~ 1

# latent outcome change variable
outcome_change =~   1*OutcomeVariable_T3
outcome_change ~ outcome_change_mean*1
outcome_change ~~ outcome_variance*outcome_change

#Constraining the stability of the outcome to 0
OutcomeVariable_T3 ~ 1*OutcomeVariable_T1
OutcomeVariable_T3 ~~ 0*OutcomeVariable_T1
OutcomeVariable_T3 ~~ 0*OutcomeVariable_T3
OutcomeVariable_T3 ~ 0
OutcomeVariable_T1 ~ 1

# Estimating the pretest correlation between M1 and Y1 and variance of X
OutcomeVariable_T1 ~~ covariance_at_T1*MediatorVariable_T1


# a path
mediator_change ~ a*Condition_Dummy

# mediator stability
mediator_change ~ mediator_stability*MediatorVariable_T1

# change in mediator regressed on baseline outcome
mediator_change ~ mediator_change_x_outcome_T1*OutcomeVariable_T1


# cprime path
outcome_change ~ cprime*Condition_Dummy

# b path
outcome_change ~ b*mediator_change

# change in outcome regressed on baseline mediator
outcome_change ~  outcome_change_x_mediator_T1*MediatorVariable_T1

# stability of outcome 
outcome_change ~ outcome_stability*OutcomeVariable_T1

# !Estimate of mediated effect;
ab := a*b

effect_size := ab/sqrt(outcome_variance)
'
  # this line inserts the actual variable names into the model syntax
  # as specified above
  mediation.model <-  str_replace_all(mediation.model.generic,
                                      c("OutcomeVariable" = outcome_var,
                                        "MediatorVariable" = mediator_var))
  # model is estimated
  mediation.fit <- lavaan::sem(model = mediation.model,
                               data = PreToPost.data,
                               bootstrap = 10000,
                               se = 'bootstrap',
                               missing = 'fiml')
  return(mediation.fit)
}


```

## EAC Models
```{r}
set.seed(1)
EAC.Mean_IESR.Total_contemporaneous.fit <- runMediationModel('EAC.Total','IESR.Total')

set.seed(1)
EAC.Mean_FCR_contemporaneous.fit <- runMediationModel('EAC.Total','FCR')


set.seed(1)
EAC.Mean_HADS.A_contemporaneous.fit <- runMediationModel('EAC.Total','HADS.A')

```

## SCS Models
```{r}
set.seed(1)
SCS_IESR.Total_contemporaneous.fit <- runMediationModel('SCS','IESR.Total')
set.seed(1)
SCS_FCR_contemporaneous.fit <- runMediationModel('SCS','FCR')
set.seed(1)
SCS_HADS.A_contemporaneous.fit <- runMediationModel('SCS','HADS.A')
```


## AAQc Models
```{r}
set.seed(1)
AAQc_IESR.Total_contemporaneous.fit <- runMediationModel('AAQc','IESR.Total')
set.seed(1)
AAQc_FCR_contemporaneous.fit <- runMediationModel('AAQc','FCR')
set.seed(1)
AAQc_HADS.A_contemporaneous.fit <- runMediationModel('AAQc','HADS.A')
```

# save model output to a file

Since these models take a long time to run,
save the actual output.

```{r}
# remove this object from the environment
# so that individual scores are not saved alongside the models
rm(PreToPost.data)
rm(runMediationModel)
# save the rest of the workspace, which is now just lavaan fit models
# and the generic functions
save.image(file = here('4 Generated Datasets', 'PrePost_mediation_models_ANCOVA_equivalent.RData'))
```