---
title: "Difference Score Mediation Models"
output: html_notebook
---

Run difference score mediation models with n = 113 (same sample as used in Pre-Post intervention network)

# read data and libraries

```{r}

library(tidyverse)
library(here)
library(lavaan)


PreToPost.data <- readRDS(file = here('4 Generated Datasets','PreToPost.data.rds')) %>%
  as_tibble() %>%
  mutate(across(.cols = HADS.A:AAQc, .fns = scale))

```


# Generic mediation model

```{r}

runMediationModel <- function(mediator_var, outcome_var) {
  mediation.model.generic <- '

MediatorVariable ~ a*Condition_Dummy
OutcomeVariable ~ b*MediatorVariable
OutcomeVariable ~ cprime*Condition_Dummy

OutcomeVariable ~~ outcome_variance*OutcomeVariable

# !Estimate of mediated effect;
ab := a*b

effect_size := ab/sqrt(outcome_variance)
'

  # this line inserts the actual variable names into the model syntax
  # as specified above
  mediation.model <-  str_replace_all(mediation.model.generic,
                                      c("OutcomeVariable" = outcome_var,
                                        "MediatorVariable" = mediator_var))
  # model is estimated
  mediation.fit <- lavaan::sem(model = mediation.model,
                               data = PreToPost.data,
                               bootstrap = 10000,
                               se = 'bootstrap',
                               missing = 'fiml')
  return(mediation.fit)
}


```

## EAC Models
```{r}
set.seed(1)
EAC.Mean_IESR.Total_contemporaneous.fit <- runMediationModel('EAC.Total','IESR.Total')

set.seed(1)
EAC.Mean_FCR_contemporaneous.fit <- runMediationModel('EAC.Total','FCR')


set.seed(1)
EAC.Mean_HADS.A_contemporaneous.fit <- runMediationModel('EAC.Total','HADS.A')

```

## SCS Models
```{r}
set.seed(1)
SCS_IESR.Total_contemporaneous.fit <- runMediationModel('SCS','IESR.Total')
set.seed(1)
SCS_FCR_contemporaneous.fit <- runMediationModel('SCS','FCR')
set.seed(1)
SCS_HADS.A_contemporaneous.fit <- runMediationModel('SCS','HADS.A')
```


## AAQc Models
```{r}
set.seed(1)
AAQc_IESR.Total_contemporaneous.fit <- runMediationModel('AAQc','IESR.Total')
set.seed(1)
AAQc_FCR_contemporaneous.fit <- runMediationModel('AAQc','FCR')
set.seed(1)
AAQc_HADS.A_contemporaneous.fit <- runMediationModel('AAQc','HADS.A')
```

# save model output to a file

Since these models take a long time to run,
save the actual output.

```{r}
# remove this object from the environment
# so that individual scores are not saved alongside the models
rm(PreToPost.data)
rm(runMediationModel)
# save the rest of the workspace, which is now just lavaan fit models
# and the generic functions
save.image(file = here('4 Generated Datasets', 'PrePost_mediation_models_difference_score_May30.RData'))
```